const Game1Constants = {
    SET_USER_ANSWER: 'SET_USER_ANSWER',
    SET_MOUSE_COORDINATES: 'SET_MOUSE_COORDINATES',
    SET_CURRENT_LEVEL: 'SET_CURRENT_LEVEL',
    SET_PREVIOUS_LEVEL: 'SET_PREVIOUS_LEVEL'
};

export default Game1Constants;
